"""PRM-157: the audit log

Append-only: nothing in the application updates or deletes a row, and the table
carries no path that would. Retention, when it is needed, is an operator decision
with its own revision rather than something the writer does silently.

Two indexes and no more: an auditor reads by time, and by actor when following one
person. Anything else is a scan over a table that is small by construction, and an
index nobody uses is a write cost on the hot path of every admin action.

Revision ID: c18efe1007fc
Revises: c73f1a8e5b02
Create Date: 2026-09-26 20:22:39.087694
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c18efe1007fc"
down_revision: str | None = "c73f1a8e5b02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_TABLE = "audit_events"


def _has_table() -> bool:
    return _TABLE in sa.inspect(op.get_bind()).get_table_names()


def upgrade() -> None:
    # Guarded because the pre-Alembic adoption path runs `Base.metadata.create_all`
    # from *today's* models before stamping the baseline, so a database adopted
    # after this revision was written already has the table. db.py's own comment
    # warns about exactly this, and the migration tests are what caught its
    # absence here.
    if _has_table():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_client_id", sa.String(length=64), nullable=True),
        sa.Column("actor_user_id", sa.String(length=64), nullable=True),
        sa.Column("actor_email", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_events_actor", ["actor_client_id", "at"], unique=False)
        batch_op.create_index("ix_audit_events_at", ["at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    if not _has_table():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_events_at")
        batch_op.drop_index("ix_audit_events_actor")

    op.drop_table("audit_events")
    # ### end Alembic commands ###
