"""PRM-160: traffic splits

Revision ID: e42ed3dc8f09
Revises: c18efe1007fc
Create Date: 2026-09-26 21:02:56.247236
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e42ed3dc8f09"
down_revision: str | None = "c18efe1007fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_TABLE = "traffic_splits"


def _has_table() -> bool:
    return _TABLE in sa.inspect(op.get_bind()).get_table_names()


def upgrade() -> None:
    # Guarded: the pre-Alembic adoption path runs create_all from today's models
    # before stamping the baseline, so a database adopted after this was written
    # already has the table. PRM-157 forgot this guard and the migration tests
    # caught it; this is the same lesson, applied without being taught twice.
    if _has_table():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "traffic_splits",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("variants", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    if not _has_table():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("traffic_splits")
    # ### end Alembic commands ###
