"""RM-99: manager catalog snapshot

Revision ID: f78b6d4f8ca9
Revises: 88e6d866d34c
Create Date: 2026-09-14 06:37:56.785951
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f78b6d4f8ca9"
down_revision: str | None = "88e6d866d34c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Guarded like every migration since RM-68: this project adopted Alembic
    # after the fact, so a database older than the baseline has its missing
    # tables filled in by create_all() from today's models.
    if "manager_catalog_snapshot" in sa.inspect(op.get_bind()).get_table_names():
        return
    op.create_table(
        "manager_catalog_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("written_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manager_catalog_snapshot")
    # ### end Alembic commands ###
