"""baseline: schema as of PRM-153

The starting point for Alembic in auth-service — docs/roadmap.md PRM-153.
Everything here already exists in any database created before migrations were
adopted, so `create_tables()` brings such a database up to this exact shape and
then **stamps** this revision instead of running it. A brand-new database runs it
normally.

`nodes` is included because it is still in the models and still in every existing
database: PRM-134 moved the node registry to the fleet coordinator and left the
table behind on purpose as the rollback path. Dropping it is the first thing this
mechanism makes possible and is deliberately not done here — a rollback path
removed the same day it was created is not a rollback path.


Revision ID: f7060a106063
Revises:
Create Date: 2026-09-26 18:05:14.726025
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f7060a106063"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("manager_url", sa.String(length=512), nullable=False),
        sa.Column("node_type", sa.Enum("mac", "nvidia", "other", name="nodetype"), nullable=False),
        sa.Column("tag", sa.Text(), nullable=True),
        sa.Column("hourly_cost_usd", sa.Float(), nullable=True),
        sa.Column("hardware_amortization_usd_per_hour", sa.Float(), nullable=False),
        sa.Column("electricity_usd_per_hour", sa.Float(), nullable=False),
        sa.Column("price_margin_multiplier", sa.Float(), nullable=False),
        sa.Column("engines", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "principals",
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("auth_method", sa.String(length=16), nullable=False),
        sa.Column("client_secret_hash", sa.String(length=60), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=60), nullable=True),
        sa.Column(
            "role",
            sa.Enum("admin", "cognitive", "agent", "app", name="principalrole"),
            nullable=False,
        ),
        sa.Column("allowed_scopes", sa.Text(), nullable=False),
        sa.Column("token_ttl_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("client_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "credential_share_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("client_id_value", sa.String(length=36), nullable=False),
        sa.Column("secret_plaintext_enc", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by_ip", sa.String(length=45), nullable=True),
        sa.Column("used_by_ua", sa.Text(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["principals.client_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    with op.batch_alter_table("credential_share_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_share_tokens_client_id", ["client_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credential_share_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_share_tokens_client_id")

    op.drop_table("credential_share_tokens")
    op.drop_table("principals")
    op.drop_table("nodes")
    # ### end Alembic commands ###
